# Chapter 6 Using Iteration (with_item) to install Multiple Packages
- name: Using Iteration (with_item) to install multiple packages
  hosts: geni
#  sudo: True 這邊學到 sudo 不一定要放在一般選項內, 也可以放在 task 內
  tasks:
    - name: install apt packages
# 於 apt moudule 使用 sudo
      sudo: True
# 使用 pkg 加上 {{ item }} 配合後面的 with_item 來安裝多個套件
      apt: pkg={{ item }} update_cache=yes cache_valid_time=3600
# 配合前面的 {{ item }} 來安裝多套件
      with_items:
        - openjdk-7-jdk
        - wget
        - scala

# 由於沒有在 general option 使用 sudo, 這邊在使用 shell module 抓下來就是使用者自己的身份額非 root
    - name: Download spark with pre-build hadoop
      shell: wget    http://archive.apache.org/dist/spark/spark-1.4.0/spark-1.4.0-bin-hadoop2.6.tgz

# 解開 source code
    - name: Exact pre-build source
      shell: tar zxvf spark-*.tgz

    - name: Rename spark folder
      shell: mv ~/spark*/ ~/spark
# 這邊利用 register 以及 後面的 debug 來取得輸出
    - name: Show scala package
      shell: apt-cache showpkg scala
      register: scala
# 這邊可以利用 var=scala 先觀察輸出的資料, 在指定輸出的範圍, 這邊用 .stdout_lines
    - debug: var=scala.stdout_lines

# 測試 jps 指令
    - name: Testing jps command
      command: jps
      register: jps
    - debug: var=jps.stdout_lines
