# Chapter 6 Using Iteration (with_item) to install Multiple Packages
- name: psing Iteration (with_item) to install multiple packages
  hosts: utah_master
#  sudo: True 這邊學到 sudo 不一定要放在一般選項內, 也可以放在 task 內

  tasks:
    - name: install python-pip
# 於 apt moudule 使用 sudo
      sudo: True
# 安裝 python-pip 套件
      apt: name=python-pip update_cache=yes cache_valid_time=3600

# 顯示目前 pip 裡面有的相關 python 套件
    - name: show pip packages wit pip freeze
      shell: pip freeze
      register: pip
    - debug: var=pip.stdout_lines

    - name: pip install with_item
# 於 pip moudule 使用 sudo
      sudo: True
      pip: name={{ item }}
# 使用 pip 加上 {{ item }} 配合後面的 with_item 來安裝多個套件
# 配合前面的 {{ item }} 來安裝多套件
      with_items:
        - bottle
        - south

# 顯示目前 pip 裡面有的相關 python 套件
    - name: show pip packages wit pip freeze
      shell: pip freeze
      register: pip
    - debug: var=pip.stdout_lines

